# -- Main Menu --

[[main]]
  name = "home"
  pageRef = "/"
  weight = 1

[[main]]
  name = "about"
  pageRef = "/about"
  weight = 2

[[main]]
  name = "posts"
  pageRef = "/posts"
  weight = 3

[[main]]
  name = "blogroll"
  pageRef = "/fav-blogs"
  weight = 4

[[main]]
  identifier = "search"
  weight = 98
  [main.params]
    action = "search"

# add this near the end so it shows on the right
[[main]]
  identifier = "appearance"
  weight = 99
  [main.params]
    action = "appearance"     # optional: hide the label and show only icon
